name: buildacar
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.3 # Firebase Database
  firebase_auth: ^4.7.1
  email_validator: '^2.1.16'
  flutter_svg: ^2.0.7
  image: ^4.0.17
  month_year_picker: ^0.3.0+1
  http: ^1.1.0

  mobx: ^2.0.5             # Mobx
  flutter_mobx: ^2.0.2

  flutter_slider_drawer: ^2.1.3
  favorite_button: ^0.0.4
  url_launcher: ^6.1.12

  flutter_slidable: ^3.0.0
  provider: ^6.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  flutter_launcher_icons: ^0.13.1

  #Mobx
  build_runner:
  mobx_codegen:

flutter_icons:
  android: true
  ios: true
  image_path: "lib/Build-A-Car_pictures/logo/carLogo.png"

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - lib/Build-A-Car_pictures/
     - lib/Build-A-Car_pictures/Vehicles_BAC/



