/// File generated by FlutterFire CLI.
/// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaSk7R8TceMqEBuXEZ5Qen16RlkZf5tHI',
    appId: '1:131438027933:web:695bf04078dcc4b880a074',
    messagingSenderId: '131438027933',
    projectId: 'build-a-car-a0507',
    authDomain: 'build-a-car-a0507.firebaseapp.com',
    storageBucket: 'build-a-car-a0507.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo_xYIDmmLUCBSXoS76S5-J5AUpxlXegM',
    appId: '1:131438027933:android:10435de8249ddc1280a074',
    messagingSenderId: '131438027933',
    projectId: 'build-a-car-a0507',
    storageBucket: 'build-a-car-a0507.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSUhLh0NGoNCvmKnXBRp3nhiM1uSguD-g',
    appId: '1:131438027933:ios:cd9f4d8eea435dd480a074',
    messagingSenderId: '131438027933',
    projectId: 'build-a-car-a0507',
    storageBucket: 'build-a-car-a0507.appspot.com',
    iosClientId: '131438027933-jtlci7i6gucb5cn6njrgunl69r470m3h.apps.googleusercontent.com',
    iosBundleId: 'com.example.buildacar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSUhLh0NGoNCvmKnXBRp3nhiM1uSguD-g',
    appId: '1:131438027933:ios:83c4ed085a3fe82b80a074',
    messagingSenderId: '131438027933',
    projectId: 'build-a-car-a0507',
    storageBucket: 'build-a-car-a0507.appspot.com',
    iosClientId: '131438027933-qmkuc1oggaiarddc0c9h99pvt0qnhji6.apps.googleusercontent.com',
    iosBundleId: 'com.example.buildacar.RunnerTests',
  );
}
